import React from "react";
import type { Metadata } from "next";
import { Inter as InterFont } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
//import {Archiv Grotesk,Lucida} from "next/font/google"; // need another way to load them in
import "./globals.css";
import PostHogProvider from "./PostHogProvider";

const geistSans = Geist({
  variable: "--font-secondary",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-tertiary",
  subsets: ["latin"],
});

const Inter = InterFont({
  variable: "--font-primary",
  subsets: ["latin"],
});

// actual fonts that I cannot get loaded I need to get them in another way

// const archivFont = ArchiveGrotesk
// variable:"--font-secondary" });

// const lucidaFont = Lucida
// variable:"--font-tertiary" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Inter.variable} antialiased`}
      >
        <PostHogProvider>{children}</PostHogProvider>
      </body>
    </html>
  );
}
