import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import PostHogProvider from "./PostHogProvider";

export const inter = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
});

export const archivGrotesk = localFont({
  src: [
    {
      path: "./fonts/ArchivGrotesk-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      s
      <body
        className={`${inter.variable}, ${archivGrotesk.variable} antialiased`}
      >
        <PostHogProvider>{children}</PostHogProvider>
      </body>
    </html>
  );
}
0;
